---
name: Checksum

on: 
  workflow_dispatch:
    inputs:
      link1:
        description: 'Link #1'
        type: string
        required: true
      link2:
        description: 'Link #2'
        type: string
      link3:
        description: 'Link #3'
        type: string
      link4:
        description: 'Link #4'
        type: string
      link5:
        description: 'Link $5'
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checksum
        run: |
          wget -q \
            ${{ inputs.link1 }} \
            ${{ inputs.link2 }} \
            ${{ inputs.link3 }} \
            ${{ inputs.link4 }} \
            ${{ inputs.link5 }}
          ls -l
          shasum -a 256 ./*
...
